on: push
name: Build and Publish
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Lint
      uses: actions/npm@master
      with:
        args: run lint
    - name: Build
      uses: actions/npm@master
      with:
        args: run build
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
